import Head from "next/head";
import { Inter } from "@next/font/google";
import NavBar from "../components/navBar";
import { Form } from "@web3uikit/core";

import { useMemo, useState, useEffect } from "react";
import {
  ConnectionProvider,
  WalletProvider,
} from "@solana/wallet-adapter-react";
import { WalletAdapterNetwork } from "@solana/wallet-adapter-base";
import {
  GlowWalletAdapter,
  PhantomWalletAdapter,
  SlopeWalletAdapter,
  SolflareWalletAdapter,
  TorusWalletAdapter,
} from "@solana/wallet-adapter-wallets";
import {
  WalletModalProvider,
  WalletMultiButton,
} from "@solana/wallet-adapter-react-ui";
import { clusterApiUrl } from "@solana/web3.js";
import { MetaplexProvider } from "./MetaplexProvider";
import "@solana/wallet-adapter-react-ui/styles.css";

import { app, database } from "./firebaseConfig";
import { collection, addDoc, getDocs } from "firebase/firestore";

export default function Home() {
  const [network, setNetwork] = useState(WalletAdapterNetwork.Devnet);

  const endpoint = useMemo(() => clusterApiUrl(network), [network]);
  const dbInstance = collection(database, '/MerchantCollection');

  const wallets = useMemo(
    () => [
      new PhantomWalletAdapter(),
      new GlowWalletAdapter(),
      new SlopeWalletAdapter(),
      new SolflareWalletAdapter({ network }),
      new TorusWalletAdapter(),
    ],
    [network]
  );

  const handleChange = (event: { target: { value: any } }) => {
    switch (event.target.value) {
      case "devnet":
        setNetwork(WalletAdapterNetwork.Devnet);
        break;
      case "mainnet":
        setNetwork(WalletAdapterNetwork.Mainnet);
        break;
      case "testnet":
        setNetwork(WalletAdapterNetwork.Testnet);
        break;
      default:
        setNetwork(WalletAdapterNetwork.Devnet);
        break;
    }
  };

  async function formHandler(event: any) {
    // Get data from the form.
    console.log(event);
    const image = event.data[8].inputResult;
    // save image in local directory from form reponse

    const metadata = {
      title: event.data[1].inputResult,
      symbol: event.data[2].inputResult,
      description: event.data[3].inputResult,
      image:
        "https://ipfs.io/ipfs/QmV1EYP9co69TVGF2GXzbyVXUrSXuJnGYje7JzQrzpDngY",
      attributes: [
        { trait_type: "Membership", value: event.data[4].inputResult },
        { trait_type: "Redemption points", value: event.data[5].inputResult },
        { trait_type: "Valid till", value: event.data[6].inputResult },
        { trait_type: "owner", value: "@jackDorsey101" },
        { trait_type: "expired", value: "false" },
      ],
      properties: {
        files: [
          {
            uri: "https://ipfs.io/ipfs/QmV1EYP9co69TVGF2GXzbyVXUrSXuJnGYje7JzQrzpDngY",
            type: "image/png",
          },
        ],
        category: null,
      },
    };

    const mintData = {
      Image: "QmV1EYP9co69TVGF2GXzbyVXUrSXuJnGYje7JzQrzpDngY",
      Symbol: event.data[2].inputResult,
      Title: event.data[1].inputResult,
      URI: "QmXhBer1sJgHvqdgs5Akiz5QJhyfxiiLHgNMhpb9vnRM3F",
      maxSupply: event.data[7].inputResult,
      merchantName: event.data[0].inputResult,
    };
    console.log("metadata: ", metadata);

    // upload metadata to ipfs using /uploadData endpoint

    // upload document to firebase
    const uploadMerchantData = () => {
      addDoc(dbInstance, mintData).then(() => {
        console.log("uploaded form data");
        window.location.reload(false)
      });
    };

    uploadMerchantData();
    
  }

  return (
    <>
      <Head>
        <title>Treehoppers Merchant Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ConnectionProvider endpoint={endpoint}>
        <WalletProvider wallets={wallets} autoConnect>
          <WalletModalProvider>
            <MetaplexProvider>
              <main>
                <NavBar onClusterChange={handleChange} />

                <div className="flex justify-center h-screen">
                  <Form
                    buttonConfig={{
                      theme: "primary",
                    }}
                    data={[
                      {
                        inputWidth: "100%",
                        name: "Merchant Name",
                        type: "text",
                        value: "",
                      },
                      {
                        inputWidth: "100%",
                        name: "Coupon Title",
                        type: "text",
                        value: "",
                      },                    
                      {
                        inputWidth: "100%",
                        name: "Symbol",
                        type: "text",
                        value: "",
                      },
                      {
                        inputWidth: "100%",
                        name: "Description",
                        type: "text",
                        value: "",
                      },   
                      {
                        inputWidth: "100%",
                        name: "Membership Level",
                        type: "text",
                        value: "",
                      },                                         
                      {
                        name: "Redemption Points",
                        type: "number",
                        value: "",
                      },
                      {
                        name: "Date of Expiry",
                        type: "date",
                        value: "",
                      },
                      {
                        name: "Supply",
                        type: "number",
                        value: "",
                      },
                      {
                        inputWidth: '100%',
                        name: 'Image',
                        type: 'file',
                        value: ''
                      },                  

                    ]}
                    onSubmit={formHandler}
                    title="Add Coupons"
                  />
                </div>
              </main>
            </MetaplexProvider>
          </WalletModalProvider>
        </WalletProvider>
      </ConnectionProvider>
    </>
  );
}
