import Head from "next/head";
import { Inter } from "@next/font/google";
import NavBar from "../components/navBar";
import Dash2 from "../components/dashboard";
import "@solana/wallet-adapter-react-ui/styles.css";

const inter = Inter({ subsets: ["latin"] });

export default function App() {
  return (
    <>
      <Head>
        <title>Treehoppers Merchant Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <NavBar />
        <Dash2 />
      </main>
    </>
  );
}
