import Navbar from '../components/navBar'
import Head from 'next/head'

export default function PendingClaims() {
    return (
      <>
      <Head>
        <title>Treehoppers Merchant Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
          <Navbar />
          <h1 className='px-6 py-6 text-4xl font-bold text-center'>Coming Soon!</h1>
        </main>
      </>
    )
  }